"""add_knowledge_bases_and_kb_id

Revision ID: 49426109cb1d
Revises: 0c1c9d0abd67
Create Date: 2026-07-14 20:48:59.906503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49426109cb1d'
down_revision: Union[str, None] = '0c1c9d0abd67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_bases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_bases_user_id'), 'knowledge_bases', ['user_id'], unique=False)
    op.add_column('knowledge_items', sa.Column('kb_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_knowledge_items_kb_id'), 'knowledge_items', ['kb_id'], unique=False)
    op.create_foreign_key(None, 'knowledge_items', 'knowledge_bases', ['kb_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge_items', type_='foreignkey')
    op.drop_index(op.f('ix_knowledge_items_kb_id'), table_name='knowledge_items')
    op.drop_column('knowledge_items', 'kb_id')
    op.drop_index(op.f('ix_knowledge_bases_user_id'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    # ### end Alembic commands ###
